### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by Sirfrancis18** [roshanconnor123/fclone_android#2]
Hi
Thank you for your work 
do you plan to port the gclone for android?
I say this because fclone doubles or triples files. It doesn't matter which filter you put (ignore existing, ignore size, etc)
with rclone it does not happen to me and it makes everything perfect
with fclone I have tried it many times with different folders and it creates clones for me, duplicate folders disappear. then with dedupe they appear again, but before you have had to delete thousands of files

**Comment by roshanconnor123** [comment]
There you go
https://github.com/roshanconnor123/gclone_android

**Comment by Sirfrancis18** [comment]
thanks. i try bit cant download 
 wget https://3.roshansmirror.workers.dev/gclone

**Comment by roshanconnor123** [comment]
Updated it..check now pls

**Comment by Sirfrancis18** [comment]
work. thanks. I am testing your other repositories. great job
